<form method="post" action="{$request_uri}app/database-config" style="width: 80%">
  <h1>TERMO DE USO - LICENÇA</h1>
  <div class="inset">
  <p>
    <ol>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nunc enim, placerat vitae nunc eget, ornare vulputate ipsum. Ut a lacus id quam tempor eleifend vitae in arcu. Nullam molestie, lectus et rutrum lacinia, metus nunc pharetra diam, non molestie lorem tellus id mi. Pellentesque convallis turpis arcu, id tempus erat mattis tincidunt. Vivamus nec efficitur nunc. Suspendisse rutrum commodo est vitae aliquet. Morbi egestas ligula ex.<br/><br/></li>
    </ol>
  </p>
  </div>
  <p class="p-container">
    <input type="submit" name="go" id="go" value="Aceito">
  </p>
</form>